name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  meta_weather_api:
    path: ../meta_weather_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.12
  mocktail: ^0.2.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  coverage: ^1.0.3

flutter:
